export type DefaultWordPackDefinition = {
  key: string;
  title: string;
  icon: string;
  mode: "word";
  items: Array<{
    word: string;
    hint: string;
  }>;
};

type WordHintEntry = readonly [string, string];

const OFFICIAL_WORD_PACK_SIZES: Record<string, number> = {
  classico: 200,
  resenha: 42,
  futebol: 40,
  "area-da-saude": 40,
  tecnologia: 40,
  disney: 40,
  "harry-potter": 40,
  naruto: 40,
  valorant: 40,
  "league-of-legends": 40,
  minecraft: 40,
  "one-piece": 40,
  fortnite: 40,
  pokemon: 40,
  "star-wars": 40,
  "game-of-thrones": 40,
  "jujutsu-kaisen": 40,
  "demon-slayer": 40,
  friends: 40,
  clash: 40,
};

const LEGACY_WORD_PACK_TITLES: Record<string, string[]> = {
  classico: ["Classico"],
  "area-da-saude": ["Area da Saude"],
  pokemon: ["Pokemon"],
};

const OFFICIAL_WORD_PACK_BANNED_HINTS: Record<string, string[]> = {
  disney: ["disney"],
  "harry-potter": ["harry", "potter"],
  naruto: ["naruto"],
  valorant: ["valorant"],
  "league-of-legends": ["league", "legends", "lol"],
  minecraft: ["minecraft"],
  "one-piece": ["onepiece", "one", "piece"],
  fortnite: ["fortnite"],
  pokemon: ["pokemon", "pokémon", "poke"],
  "star-wars": ["star", "wars"],
  "game-of-thrones": ["game", "thrones", "got"],
  "jujutsu-kaisen": ["jujutsu", "kaisen"],
  "demon-slayer": ["demon", "slayer"],
  friends: ["friends"],
  clash: ["clash", "royale", "clans"],
};

function buildWordItems(entries: readonly WordHintEntry[]) {
  return entries.map(([word, hint]) => ({ word, hint }));
}

function normalizeToken(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function getTokens(value: string) {
  return normalizeToken(value).split(/\s+/).filter(Boolean);
}

function assertDefaultWordPacks(packs: DefaultWordPackDefinition[]) {
  const seenPackKeys = new Set<string>();

  for (const pack of packs) {
    if (seenPackKeys.has(pack.key)) {
      throw new Error(`Pack duplicado no catalogo oficial: ${pack.key}`);
    }
    seenPackKeys.add(pack.key);

    const expectedSize = OFFICIAL_WORD_PACK_SIZES[pack.key];
    if (!expectedSize) {
      throw new Error(`Pack oficial sem contagem esperada: ${pack.key}`);
    }
    if (pack.items.length !== expectedSize) {
      throw new Error(
        `Pack ${pack.key} deve ter ${expectedSize} itens, mas possui ${pack.items.length}.`
      );
    }

    const seenWords = new Set<string>();
    const bannedHintTokens = new Set<string>([
      ...getTokens(pack.title),
      ...(OFFICIAL_WORD_PACK_BANNED_HINTS[pack.key] ?? []).flatMap(getTokens),
    ]);

    for (const item of pack.items) {
      const normalizedWord = normalizeToken(item.word);
      const normalizedHint = normalizeToken(item.hint);
      const hintTokens = item.hint.trim().split(/\s+/).filter(Boolean);
      const wordTokens = getTokens(item.word);

      if (!normalizedWord) {
        throw new Error(`Pack ${pack.key} contem palavra vazia.`);
      }
      if (!normalizedHint) {
        throw new Error(`Pack ${pack.key} contem hint vazia para ${item.word}.`);
      }
      if (hintTokens.length !== 1) {
        throw new Error(`Hint invalida em ${pack.key}/${item.word}: ${item.hint}`);
      }
      if (seenWords.has(normalizedWord)) {
        throw new Error(`Palavra duplicada em ${pack.key}: ${item.word}`);
      }
      if (normalizedWord === normalizedHint) {
        throw new Error(`Hint igual a palavra em ${pack.key}: ${item.word}`);
      }
      if (wordTokens.includes(normalizedHint)) {
        throw new Error(`Hint trivial em ${pack.key}: ${item.word} -> ${item.hint}`);
      }
      if (bannedHintTokens.has(normalizedHint)) {
        throw new Error(`Hint usa termo da franquia em ${pack.key}: ${item.word} -> ${item.hint}`);
      }

      seenWords.add(normalizedWord);
    }
  }
}

export function getWordPackCategoryAliases(
  pack: Pick<DefaultWordPackDefinition, "key" | "title">
) {
  return Array.from(new Set([pack.title, ...(LEGACY_WORD_PACK_TITLES[pack.key] ?? [])]));
}

export const DEFAULT_WORD_PACKS: DefaultWordPackDefinition[] = [
  {
    key: "classico",
    title: "Clássico",
    icon: "star",
    mode: "word",
    items: buildWordItems([
      ["Abajur", "luz"],
      ["Agenda", "compromisso"],
      ["Agasalho", "inverno"],
      ["Alarme", "acordar"],
      ["Almofada", "sofá"],
      ["Apito", "árbitro"],
      ["Aquário", "peixe"],
      ["Armário", "roupa"],
      ["Aspirador", "poeira"],
      ["Avental", "cozinha"],
      ["Balde", "limpeza"],
      ["Banco", "agência"],
      ["Bandeja", "garçom"],
      ["Baralho", "naipe"],
      ["Barraca", "feirante"],
      ["Bicicleta", "pedal"],
      ["Binóculo", "distância"],
      ["Bola", "quadra"],
      ["Bolsa", "ombro"],
      ["Borracha", "caderno"],
      ["Cadeira", "descanso"],
      ["Caderno", "anotação"],
      ["Cafeteira", "manhã"],
      ["Caixa", "presente"],
      ["Calculadora", "conta"],
      ["Calendário", "data"],
      ["Caneca", "café"],
      ["Caneta", "tinta"],
      ["Capa", "chuva"],
      ["Carregador", "tomada"],
      ["Carrinho", "supermercado"],
      ["Carteira", "documento"],
      ["Cartaz", "parede"],
      ["Chave", "fechadura"],
      ["Chinelo", "praia"],
      ["Chuveiro", "banho"],
      ["Cobertor", "noite"],
      ["Colchão", "sono"],
      ["Colher", "sopa"],
      ["Computador", "mouse"],
      ["Copo", "sede"],
      ["Cortina", "janela"],
      ["Creme dental", "dentes"],
      ["Despertador", "horário"],
      ["Dicionário", "significado"],
      ["Edredom", "frio"],
      ["Elevador", "prédio"],
      ["Enxada", "horta"],
      ["Escada", "degrau"],
      ["Escova", "cabelo"],
      ["Espelho", "reflexo"],
      ["Espremedor", "suco"],
      ["Estojo", "escola"],
      ["Etiqueta", "preço"],
      ["Extensão", "fio"],
      ["Faca", "cozinha"],
      ["Fichário", "aula"],
      ["Filtro", "água"],
      ["Fogão", "panela"],
      ["Fone", "ouvido"],
      ["Fralda", "bebê"],
      ["Frasco", "perfume"],
      ["Frigideira", "ovo"],
      ["Furadeira", "parede"],
      ["Garfo", "jantar"],
      ["Garrafa", "sede"],
      ["Gaveta", "roupa"],
      ["Geladeira", "gelo"],
      ["Grampo", "cabelo"],
      ["Guarda-chuva", "tempestade"],
      ["Guitarra", "palco"],
      ["Helicóptero", "hélice"],
      ["Imã", "geladeira"],
      ["Impressora", "papel"],
      ["Interruptor", "lâmpada"],
      ["Jaqueta", "frio"],
      ["Janela", "ventilação"],
      ["Jarra", "suco"],
      ["Lâmpada", "teto"],
      ["Lancheira", "recreio"],
      ["Lanterna", "escuro"],
      ["Lápis", "desenho"],
      ["Lava-louças", "cozinha"],
      ["Liquidificador", "vitamina"],
      ["Livro", "leitura"],
      ["Lixeira", "resíduo"],
      ["Mala", "viagem"],
      ["Martelo", "prego"],
      ["Máscara", "fantasia"],
      ["Meia", "calçado"],
      ["Mesa", "almoço"],
      ["Mochila", "costa"],
      ["Molho", "macarrão"],
      ["Monitor", "tela"],
      ["Moeda", "troco"],
      ["Mouse", "clique"],
      ["Óculos", "visão"],
      ["Panela", "fogo"],
      ["Pano", "poeira"],
      ["Papel", "bilhete"],
      ["Pasta", "escritório"],
      ["Patins", "rodinha"],
      ["Peneira", "farinha"],
      ["Pente", "cabelo"],
      ["Perfume", "aroma"],
      ["Peteca", "brincadeira"],
      ["Pia", "torneira"],
      ["Pincel", "tinta"],
      ["Pipoca", "cinema"],
      ["Pneu", "asfalto"],
      ["Porta", "campainha"],
      ["Prato", "refeição"],
      ["Pulseira", "pulso"],
      ["Quadro", "sala"],
      ["Rádio", "frequência"],
      ["Relógio", "atraso"],
      ["Régua", "medida"],
      ["Rodo", "chão"],
      ["Roteador", "sinal"],
      ["Sabonete", "espuma"],
      ["Sacola", "mercado"],
      ["Saco", "lixo"],
      ["Sandália", "verão"],
      ["Shampoo", "banho"],
      ["Sino", "escola"],
      ["Sofá", "sala"],
      ["Sombrinha", "sol"],
      ["Talher", "refeição"],
      ["Tapete", "chão"],
      ["Telefone", "ligação"],
      ["Televisão", "controle"],
      ["Termômetro", "temperatura"],
      ["Tesoura", "corte"],
      ["Tigela", "cereal"],
      ["Toalha", "banho"],
      ["Torneira", "pia"],
      ["Travesseiro", "cama"],
      ["Trem", "trilho"],
      ["Troféu", "vitória"],
      ["Ventilador", "calor"],
      ["Vassoura", "varrer"],
      ["Violão", "cordas"],
      ["Xícara", "pires"],
      ["Zebra", "faixa"],
      ["Açougue", "carne"],
      ["Aeroporto", "embarque"],
      ["Apartamento", "condomínio"],
      ["Barbearia", "tesoura"],
      ["Biblioteca", "silêncio"],
      ["Bilheteria", "ingresso"],
      ["Cabine", "pedágio"],
      ["Cafeteria", "expresso"],
      ["Camping", "barraca"],
      ["Cartório", "registro"],
      ["Castelo", "torre"],
      ["Cemitério", "lápide"],
      ["Cinema", "trailer"],
      ["Clínica", "consulta"],
      ["Cozinha", "receita"],
      ["Delegacia", "boletim"],
      ["Escola", "recreio"],
      ["Estádio", "torcida"],
      ["Farmácia", "remédio"],
      ["Feira", "barraca"],
      ["Floresta", "trilha"],
      ["Garagem", "carro"],
      ["Hospital", "plantão"],
      ["Hotel", "hospedagem"],
      ["Igreja", "altar"],
      ["Mercado", "oferta"],
      ["Museu", "exposição"],
      ["Padaria", "pão"],
      ["Parque", "balanço"],
      ["Piscina", "mergulho"],
      ["Pizzaria", "forno"],
      ["Portão", "campainha"],
      ["Praia", "areia"],
      ["Praça", "banco"],
      ["Restaurante", "cardápio"],
      ["Rodoviária", "plataforma"],
      ["Salão", "espelho"],
      ["Supermercado", "carrinho"],
      ["Teatro", "plateia"],
      ["Zoológico", "jaula"],
      ["Advogado", "tribunal"],
      ["Arquiteto", "planta"],
      ["Bombeiro", "mangueira"],
      ["Cabeleireiro", "penteado"],
      ["Carteiro", "envelope"],
      ["Cozinheiro", "tempero"],
      ["Dentista", "broca"],
      ["Enfermeira", "curativo"],
      ["Engenheiro", "obra"],
      ["Fotógrafo", "retrato"],
      ["Jardineiro", "regador"],
      ["Jornalista", "manchete"],
      ["Motorista", "volante"],
      ["Pedreiro", "cimento"],
      ["Professor", "lousa"],
      ["Veterinário", "pet"],
    ]),
  },
  {
    key: "resenha",
    title: "Resenha",
    icon: "crown",
    mode: "word",
    items: buildWordItems([
      ["Gui", "risada"],
      ["Jean", "conversa"],
      ["Luan", "criador"],
      ["JosÃ©", "estrada"],
      ["Chequer", "rotina"],
      ["Ian", "lealdade"],
      ["Rafael", "estrategia"],
      ["Dorea", "corrida"],
      ["Sir Grisha", "nobre"],
      ["Luca", "caos"],
      ["SÃ£o Jorge", "coragem"],
      ["Faculdade de IlhÃ©us", "campus"],
      ["Nelson Costa", "bairro"],
      ["Titi", "zoom"],
      ["Zui", "viagem"],
      ["Marco", "comando"],
      ["Jeffrson", "agito"],
      ["Caio ConceiÃ§Ã£o", "estilo"],
      ["Caio Bigo", "postura"],
      ["Vida", "energia"],
      ["JoÃ£o Pedro", "torcida"],
      ["Enzo Nunes", "sumico"],
      ["Maria Sofia", "festa"],
      ["Matteo", "curva"],
      ["Memi", "elegancia"],
      ["VH", "impulso"],
      ["Zagaya", "lanche"],
      ["Henry", "legado"],
      ["Steam Bunch", "equipe"],
      ["Premier League iOS", "tabela"],
      ["Guirj", "praia"],
      ["Marcelo", "detetive"],
      ["Gabriel Sheese", "humor"],
      ["Pablo", "presenca"],
      ["ArmazÃ©m73", "balcao"],
      ["Kanye West", "album"],
      ["BogotÃ¡", "altitude"],
      ["Mudae", "colecao"],
      ["Kodai", "truque"],
      ["Guto", "piada"],
      ["Pedrinho", "foco"],
      ["Alessandra", "pausa"],
    ]),
  },
  {
    key: "futebol",
    title: "Futebol",
    icon: "football",
    mode: "word",
    items: buildWordItems([
      ["Bola", "gramado"],
      ["Trave", "gol"],
      ["Rede", "balanço"],
      ["Escanteio", "bandeira"],
      ["Falta", "apito"],
      ["Pênalti", "marca"],
      ["Impedimento", "linha"],
      ["Chuteira", "travinha"],
      ["Gramado", "corte"],
      ["Goleiro", "luva"],
      ["Zagueiro", "corte"],
      ["Lateral", "corredor"],
      ["Volante", "marcação"],
      ["Meia", "criação"],
      ["Centroavante", "área"],
      ["Capitão", "braçadeira"],
      ["Bandeirinha", "sinal"],
      ["Cartão amarelo", "advertência"],
      ["Cartão vermelho", "expulsão"],
      ["VAR", "revisão"],
      ["Torcida", "canto"],
      ["Arquibancada", "degrau"],
      ["Drible", "ginga"],
      ["Chapéu", "elevação"],
      ["Caneta", "meio"],
      ["Cabeceio", "cruzamento"],
      ["Bicicleta", "acrobacia"],
      ["Tabela", "toque"],
      ["Contra-ataque", "velocidade"],
      ["Libertadores", "continente"],
      ["Brasileirão", "pontos"],
      ["Maracanã", "rio"],
      ["Seleção", "convocação"],
      ["Camisa 10", "criatividade"],
      ["Escudo", "clube"],
      ["Uniforme", "listras"],
      ["Técnico", "prancheta"],
      ["Apito", "árbitro"],
      ["Escalação", "titular"],
      ["Rebaixamento", "queda"],
    ]),
  },
  {
    key: "area-da-saude",
    title: "Área da Saúde",
    icon: "health",
    mode: "word",
    items: buildWordItems([
      ["Hospital", "plantão"],
      ["Clínica", "consulta"],
      ["Ambulância", "sirene"],
      ["Estetoscópio", "ausculta"],
      ["Seringa", "dose"],
      ["Curativo", "gaze"],
      ["Termômetro", "medição"],
      ["Cirurgia", "centro"],
      ["Tomografia", "imagem"],
      ["Radiografia", "raio"],
      ["Vacina", "campanha"],
      ["Receita", "prescrição"],
      ["Plantão", "turno"],
      ["Leito", "internação"],
      ["Triagem", "prioridade"],
      ["UTI", "monitor"],
      ["Consulta", "agendamento"],
      ["Diagnóstico", "laudo"],
      ["Sintoma", "sinal"],
      ["Febre", "termômetro"],
      ["Pressão", "braçadeira"],
      ["Hemograma", "sangue"],
      ["Bisturi", "incisão"],
      ["Anestesia", "sedação"],
      ["Fisioterapia", "reabilitação"],
      ["Psicologia", "escuta"],
      ["Nutrição", "dieta"],
      ["Pediatria", "infância"],
      ["Cardiologia", "coração"],
      ["Ortopedia", "osso"],
      ["Neurologia", "cérebro"],
      ["Dentista", "molar"],
      ["Enfermeiro", "cuidado"],
      ["Farmácia", "balcão"],
      ["Laboratório", "amostra"],
      ["Bactéria", "colônia"],
      ["Vírus", "contágio"],
      ["Imunidade", "defesa"],
      ["Reabilitação", "retorno"],
      ["Máscara", "proteção"],
    ]),
  },
  {
    key: "tecnologia",
    title: "Tecnologia",
    icon: "laptop",
    mode: "word",
    items: buildWordItems([
      ["Celular", "toque"],
      ["Notebook", "dobradiça"],
      ["Tablet", "tela"],
      ["Monitor", "pixels"],
      ["Teclado", "atalho"],
      ["Mouse", "cursor"],
      ["Servidor", "rack"],
      ["Processador", "clock"],
      ["Memória RAM", "temporário"],
      ["Placa-mãe", "slot"],
      ["Nuvem", "sincronização"],
      ["Banco de dados", "consulta"],
      ["Algoritmo", "lógica"],
      ["Código", "sintaxe"],
      ["Bug", "falha"],
      ["Firewall", "bloqueio"],
      ["Bluetooth", "pareamento"],
      ["Wi-Fi", "roteador"],
      ["Aplicativo", "ícone"],
      ["Sistema operacional", "interface"],
      ["Android", "robô"],
      ["Windows", "janela"],
      ["Linux", "terminal"],
      ["Console", "joystick"],
      ["Controle", "botão"],
      ["Streaming", "catálogo"],
      ["Podcast", "microfone"],
      ["Inteligência artificial", "modelo"],
      ["Robótica", "automação"],
      ["Drone", "hélice"],
      ["Impressora 3D", "camada"],
      ["SSD", "gravação"],
      ["Backup", "cópia"],
      ["Senha", "acesso"],
      ["Biometria", "digital"],
      ["Criptografia", "chave"],
      ["Navegador", "aba"],
      ["Frontend", "layout"],
      ["Backend", "servidor"],
      ["API", "integração"],
    ]),
  },
  {
    key: "disney",
    title: "Disney",
    icon: "castle",
    mode: "word",
    items: buildWordItems([
      ["Mickey", "rato"],
      ["Minnie", "laço"],
      ["Donald", "marinheiro"],
      ["Pateta", "desastrado"],
      ["Cinderela", "sapato"],
      ["Bela", "biblioteca"],
      ["Ariel", "oceano"],
      ["Moana", "ilha"],
      ["Stitch", "havaí"],
      ["Simba", "savana"],
      ["Mufasa", "penhasco"],
      ["Scar", "cicatriz"],
      ["Aladdin", "tapete"],
      ["Jafar", "cobra"],
      ["Gênio", "desejo"],
      ["Rapunzel", "torre"],
      ["Elsa", "gelo"],
      ["Anna", "irmã"],
      ["Olaf", "verão"],
      ["Woody", "corda"],
      ["Buzz Lightyear", "infinito"],
      ["Nemo", "anêmona"],
      ["Dory", "memória"],
      ["Mirabel", "casita"],
      ["Bruno", "visão"],
      ["Mulan", "honra"],
      ["Timon", "suricato"],
      ["Pumba", "javali"],
      ["Sininho", "fada"],
      ["Peter Pan", "janela"],
      ["Cruella", "dálmata"],
      ["Malévola", "chifres"],
      ["Úrsula", "tentáculo"],
      ["Hércules", "olimpo"],
      ["Megara", "sarcasmo"],
      ["Tarzan", "cipó"],
      ["Jane", "selva"],
      ["Dumbo", "circo"],
      ["Bambi", "floresta"],
      ["Tiana", "restaurante"],
    ]),
  },
  {
    key: "harry-potter",
    title: "Harry Potter",
    icon: "bolt",
    mode: "word",
    items: buildWordItems([
      ["Harry Potter", "cicatriz"],
      ["Hermione Granger", "biblioteca"],
      ["Ron Weasley", "xadrez"],
      ["Dumbledore", "fênix"],
      ["Snape", "poção"],
      ["Voldemort", "serpente"],
      ["Hagrid", "cabana"],
      ["Draco Malfoy", "arrogância"],
      ["Sirius Black", "afilhado"],
      ["Luna Lovegood", "sonhadora"],
      ["Neville Longbottom", "coragem"],
      ["Ginny Weasley", "diário"],
      ["Dobby", "meia"],
      ["Hedwig", "coruja"],
      ["Fawkes", "cinzas"],
      ["Buckbeak", "hipogrifo"],
      ["Hogwarts", "castelo"],
      ["Sonserina", "masmorra"],
      ["Grifinória", "leão"],
      ["Corvinal", "charada"],
      ["Lufa-Lufa", "lealdade"],
      ["Quadribol", "vassoura"],
      ["Nimbus 2000", "velocidade"],
      ["Beco Diagonal", "vitrine"],
      ["Gringotes", "cofre"],
      ["Azkaban", "prisão"],
      ["Patrono", "protetor"],
      ["Varinha", "núcleo"],
      ["Horcrux", "fragmento"],
      ["Penseira", "memória"],
      ["Capa da Invisibilidade", "tecido"],
      ["Pedra Filosofal", "elixir"],
      ["Cálice de Fogo", "torneio"],
      ["Câmara Secreta", "encanamento"],
      ["Dementador", "desespero"],
      ["Basilisco", "veneno"],
      ["Pomo de Ouro", "alado"],
      ["Vira-tempo", "ampulheta"],
      ["McGonagall", "transfiguração"],
      ["Bellatrix Lestrange", "caos"],
    ]),
  },
  {
    key: "naruto",
    title: "Naruto",
    icon: "leaf",
    mode: "word",
    items: buildWordItems([
      ["Naruto Uzumaki", "raposa"],
      ["Sasuke Uchiha", "vingança"],
      ["Sakura Haruno", "força"],
      ["Kakashi Hatake", "cópia"],
      ["Hinata Hyuga", "timidez"],
      ["Shikamaru Nara", "estratégia"],
      ["Gaara", "areia"],
      ["Jiraiya", "sábio"],
      ["Tsunade", "lesma"],
      ["Orochimaru", "cobra"],
      ["Itachi Uchiha", "corvo"],
      ["Pain", "piercing"],
      ["Konan", "papel"],
      ["Madara Uchiha", "meteoro"],
      ["Obito Uchiha", "máscara"],
      ["Minato Namikaze", "teleporte"],
      ["Kushina", "corrente"],
      ["Kurama", "chakra"],
      ["Akatsuki", "manto"],
      ["Sharingan", "olho"],
      ["Byakugan", "visão"],
      ["Rinnegan", "círculos"],
      ["Rasengan", "espiral"],
      ["Chidori", "raio"],
      ["Amaterasu", "chamas"],
      ["Susanoo", "armadura"],
      ["Konoha", "aldeia"],
      ["Hokage", "chapéu"],
      ["Kunai", "lâmina"],
      ["Shuriken", "arremesso"],
      ["Selo", "caligrafia"],
      ["Anbu", "máscara"],
      ["Sannin", "lendário"],
      ["Genin", "início"],
      ["Chunin", "exame"],
      ["Jounin", "liderança"],
      ["Rock Lee", "taijutsu"],
      ["Neji Hyuga", "destino"],
      ["Temari", "leque"],
      ["Deidara", "argila"],
    ]),
  },
  {
    key: "valorant",
    title: "Valorant",
    icon: "target",
    mode: "word",
    items: buildWordItems([
      ["Jett", "adaga"],
      ["Phoenix", "chama"],
      ["Sage", "cura"],
      ["Brimstone", "orbital"],
      ["Viper", "veneno"],
      ["Sova", "rastreamento"],
      ["Cypher", "câmera"],
      ["Reyna", "devorar"],
      ["Killjoy", "torreta"],
      ["Breach", "terremoto"],
      ["Omen", "sombra"],
      ["Astra", "estrela"],
      ["Skye", "falcão"],
      ["Yoru", "fenda"],
      ["Chamber", "cartão"],
      ["Neon", "corrida"],
      ["Fade", "pesadelo"],
      ["Harbor", "maré"],
      ["Gekko", "criaturas"],
      ["Deadlock", "rede"],
      ["Raze", "explosão"],
      ["Vandal", "rajada"],
      ["Phantom", "silêncio"],
      ["Operator", "zoom"],
      ["Sheriff", "precisão"],
      ["Classic", "pistola"],
      ["Spike", "plantar"],
      ["Eco", "economia"],
      ["Ace", "eliminação"],
      ["Clutch", "pressão"],
      ["Ascent", "mercado"],
      ["Bind", "teleporte"],
      ["Haven", "três"],
      ["Split", "corda"],
      ["Lotus", "porta"],
      ["Icebox", "guindaste"],
      ["Breeze", "praia"],
      ["Sunset", "avenida"],
      ["Smoke", "cobertura"],
      ["Flash", "cegueira"],
    ]),
  },
  {
    key: "league-of-legends",
    title: "League of Legends",
    icon: "swords",
    mode: "word",
    items: buildWordItems([
      ["Ahri", "raposa"],
      ["Lux", "luz"],
      ["Garen", "demacia"],
      ["Darius", "machado"],
      ["Jinx", "caos"],
      ["Vi", "manoplas"],
      ["Caitlyn", "armadilha"],
      ["Ashe", "flecha"],
      ["Yasuo", "vento"],
      ["Yone", "máscara"],
      ["Lee Sin", "cego"],
      ["Zed", "sombra"],
      ["Teemo", "cogumelo"],
      ["Thresh", "lanterna"],
      ["Leona", "sol"],
      ["Katarina", "adaga"],
      ["Akali", "shuriken"],
      ["Vayne", "caça"],
      ["Ezreal", "manopla"],
      ["Morgana", "grilhões"],
      ["Aatrox", "espada"],
      ["Riven", "quebrada"],
      ["Sett", "arena"],
      ["Ekko", "tempo"],
      ["Barão Nashor", "buff"],
      ["Dragão", "alma"],
      ["Arauto", "olho"],
      ["Nexus", "cristal"],
      ["Rota superior", "ilha"],
      ["Selva", "acampamento"],
      ["Rota do meio", "torre"],
      ["Rota inferior", "dupla"],
      ["Suporte", "visão"],
      ["Gank", "surpresa"],
      ["Pentakill", "quinto"],
      ["Ward", "sentinela"],
      ["Smite", "caçador"],
      ["Flash", "feitiço"],
      ["Teleporte", "retorno"],
      ["Worlds", "mundial"],
    ]),
  },
  {
    key: "minecraft",
    title: "Minecraft",
    icon: "pickaxe",
    mode: "word",
    items: buildWordItems([
      ["Steve", "quadrado"],
      ["Alex", "companheira"],
      ["Creeper", "silêncio"],
      ["Zumbi", "noite"],
      ["Esqueleto", "flecha"],
      ["Enderman", "teleporte"],
      ["Aldeão", "troca"],
      ["Gólem de Ferro", "protetor"],
      ["Wither", "três"],
      ["Dragão do End", "cristal"],
      ["Nether", "lava"],
      ["End", "vazio"],
      ["Superfície", "grama"],
      ["Diamante", "azul"],
      ["Esmeralda", "aldeia"],
      ["Redstone", "circuito"],
      ["Obsidiana", "portal"],
      ["Carvão", "fornalha"],
      ["Ferro", "bigorna"],
      ["Ouro", "trilho"],
      ["Picareta", "minério"],
      ["Espada", "dano"],
      ["Machado", "tronco"],
      ["Pá", "terra"],
      ["Enxada", "plantio"],
      ["Fornalha", "combustão"],
      ["Baú", "inventário"],
      ["Bancada", "receita"],
      ["Bigorna", "reparo"],
      ["Elytra", "planar"],
      ["Tocha", "iluminação"],
      ["Balde", "ordenha"],
      ["Lava", "fogo"],
      ["Portal", "dimensão"],
      ["Beacon", "raio"],
      ["Poção", "efeito"],
      ["Arco", "distância"],
      ["Trilho", "vagão"],
      ["TNT", "detonação"],
      ["Slime", "quique"],
    ]),
  },
  {
    key: "one-piece",
    title: "One Piece",
    icon: "skull",
    mode: "word",
    items: buildWordItems([
      ["Luffy", "borracha"],
      ["Zoro", "espadas"],
      ["Nami", "clima"],
      ["Usopp", "mentira"],
      ["Sanji", "cozinha"],
      ["Chopper", "rena"],
      ["Robin", "arqueologia"],
      ["Franky", "cola"],
      ["Brook", "violino"],
      ["Jinbe", "karatê"],
      ["Shanks", "ruivo"],
      ["Ace", "fogo"],
      ["Sabo", "revolução"],
      ["Law", "cirurgia"],
      ["Buggy", "circo"],
      ["Crocodile", "gancho"],
      ["Mihawk", "falcão"],
      ["Kaido", "dragão"],
      ["Big Mom", "doces"],
      ["Doflamingo", "linhas"],
      ["Barba Branca", "terremoto"],
      ["Yamato", "algemas"],
      ["Vivi", "deserto"],
      ["Koby", "evolução"],
      ["Marinha", "justiça"],
      ["Almirante", "casaco"],
      ["Yonkou", "imperador"],
      ["Shichibukai", "acordo"],
      ["Grand Line", "correnteza"],
      ["Red Line", "barreira"],
      ["Poneglyph", "pedra"],
      ["Haki", "vontade"],
      ["Sunny", "grama"],
      ["Going Merry", "ovelha"],
      ["Wano", "samurai"],
      ["Dressrosa", "brinquedo"],
      ["Alabasta", "areia"],
      ["Marineford", "guerra"],
      ["Akuma no Mi", "poder"],
      ["Mugiwara", "chapéu"],
    ]),
  },
  {
    key: "fortnite",
    title: "Fortnite",
    icon: "blaster",
    mode: "word",
    items: buildWordItems([
      ["Ônibus de Batalha", "salto"],
      ["Vitória Royale", "coroa"],
      ["Construção", "parede"],
      ["Tempestade", "círculo"],
      ["Loot", "saque"],
      ["Baú", "raridade"],
      ["Escudo", "azul"],
      ["Slurp", "cura"],
      ["Picareta", "coleta"],
      ["Asa-delta", "descida"],
      ["Passe de Batalha", "temporada"],
      ["Tilted Towers", "cidade"],
      ["Pleasant Park", "campo"],
      ["Retail Row", "lojas"],
      ["Jonesy", "recruta"],
      ["Peely", "banana"],
      ["Fishstick", "escamas"],
      ["Raven", "penas"],
      ["Midas", "ouro"],
      ["Drift", "raposa"],
      ["Meowscles", "halteres"],
      ["Pump", "escopeta"],
      ["Scar", "lendária"],
      ["SMG", "spray"],
      ["Sniper", "mira"],
      ["Chug Jug", "garrafão"],
      ["Medkit", "curativo"],
      ["Bandagem", "envolver"],
      ["Van de Reboot", "retorno"],
      ["Emote", "dança"],
      ["Default Dance", "passinho"],
      ["Esquadrão", "time"],
      ["Dupla", "parceria"],
      ["Solo", "isolado"],
      ["Sem Construção", "movimento"],
      ["Arena", "ranqueada"],
      ["Drop", "queda"],
      ["Zona", "encolher"],
      ["Supply Drop", "caixa"],
      ["Shockwave", "impulso"],
    ]),
  },
  {
    key: "pokemon",
    title: "Pokémon",
    icon: "pokeball",
    mode: "word",
    items: buildWordItems([
      ["Pikachu", "raio"],
      ["Charmander", "cauda"],
      ["Bulbasaur", "semente"],
      ["Squirtle", "casco"],
      ["Eevee", "evolução"],
      ["Snorlax", "sono"],
      ["Mewtwo", "laboratório"],
      ["Gengar", "sombra"],
      ["Lapras", "mar"],
      ["Jigglypuff", "microfone"],
      ["Psyduck", "enxaqueca"],
      ["Magikarp", "salto"],
      ["Gyarados", "fúria"],
      ["Onix", "pedra"],
      ["Dragonite", "correio"],
      ["Vulpix", "raposa"],
      ["Arcanine", "velocidade"],
      ["Abra", "teleporte"],
      ["Alakazam", "colher"],
      ["Ditto", "cópia"],
      ["Charizard", "asa"],
      ["Blastoise", "canhão"],
      ["Venusaur", "flor"],
      ["Lucario", "aura"],
      ["Greninja", "língua"],
      ["Gardevoir", "proteção"],
      ["Sylveon", "fita"],
      ["Umbreon", "lua"],
      ["Pokébola", "captura"],
      ["Pokédex", "registro"],
      ["Ginásio", "insígnia"],
      ["Treinador", "jornada"],
      ["Professor Carvalho", "pesquisa"],
      ["Equipe Rocket", "balão"],
      ["Ash", "boné"],
      ["Misty", "bicicleta"],
      ["Brock", "panela"],
      ["Liga Pokémon", "torneio"],
      ["Kanto", "início"],
      ["Paldea", "cratera"],
    ]),
  },
  {
    key: "star-wars",
    title: "Star Wars",
    icon: "lightsaber",
    mode: "word",
    items: buildWordItems([
      ["Luke Skywalker", "fazenda"],
      ["Leia Organa", "rebeldia"],
      ["Han Solo", "contrabandista"],
      ["Chewbacca", "wookiee"],
      ["Darth Vader", "respiração"],
      ["Obi-Wan", "mestre"],
      ["Yoda", "pântano"],
      ["Anakin", "queda"],
      ["Padmé", "senadora"],
      ["Palpatine", "trono"],
      ["R2-D2", "bipe"],
      ["C-3PO", "etiqueta"],
      ["Boba Fett", "caçador"],
      ["Ahsoka", "togruta"],
      ["Grogu", "berço"],
      ["Rey", "sucata"],
      ["Finn", "deserção"],
      ["Poe Dameron", "piloto"],
      ["Kylo Ren", "conflito"],
      ["BB-8", "esfera"],
      ["Mace Windu", "roxo"],
      ["Qui-Gon", "intuição"],
      ["Dooku", "elegância"],
      ["Grievous", "coleção"],
      ["Millennium Falcon", "hiperdrive"],
      ["X-Wing", "asa"],
      ["Tie Fighter", "império"],
      ["Estrela da Morte", "superlaser"],
      ["Sabre de luz", "cristal"],
      ["Força", "equilíbrio"],
      ["Jedi", "ordem"],
      ["Sith", "lado"],
      ["Stormtrooper", "armadura"],
      ["Tatooine", "deserto"],
      ["Coruscant", "arranha-céu"],
      ["Naboo", "lagos"],
      ["Endor", "lua"],
      ["Mandalore", "credo"],
      ["Império", "domínio"],
      ["Ordem 66", "trauma"],
    ]),
  },
  {
    key: "game-of-thrones",
    title: "Game of Thrones",
    icon: "crown",
    mode: "word",
    items: buildWordItems([
      ["Jon Snow", "bastardo"],
      ["Daenerys", "dragões"],
      ["Tyrion", "vinho"],
      ["Arya", "agulha"],
      ["Sansa", "corte"],
      ["Bran", "corvo"],
      ["Ned Stark", "honra"],
      ["Cersei", "trono"],
      ["Jaime", "mão"],
      ["Joffrey", "crueldade"],
      ["Brienne", "juramento"],
      ["Samwell", "livros"],
      ["Davos", "cebola"],
      ["Melisandre", "fogo"],
      ["Bronn", "ouro"],
      ["Cão de Caça", "queimadura"],
      ["Montanha", "brutalidade"],
      ["Tywin", "legado"],
      ["Khal Drogo", "horda"],
      ["Varys", "sussurro"],
      ["Winterfell", "neve"],
      ["Porto Real", "capital"],
      ["Pedra do Dragão", "vulcão"],
      ["Muralha", "gelo"],
      ["Trono de Ferro", "lâminas"],
      ["Dothraki", "cavalaria"],
      ["Imaculados", "disciplina"],
      ["Selvagem", "norte"],
      ["Caminhante Branco", "geada"],
      ["Rei da Noite", "tempestade"],
      ["Aço valiriano", "forja"],
      ["Lobo gigante", "alcateia"],
      ["Casa Stark", "lobo"],
      ["Casa Lannister", "leão"],
      ["Casa Targaryen", "dragão"],
      ["Casamento Vermelho", "banquete"],
      ["Hodor", "porta"],
      ["Cidadela", "corrente"],
      ["Meistre", "corvo"],
      ["Westeros", "continente"],
    ]),
  },
  {
    key: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    icon: "fist",
    mode: "word",
    items: buildWordItems([
      ["Yuji Itadori", "atletismo"],
      ["Megumi Fushiguro", "sombras"],
      ["Nobara Kugisaki", "martelo"],
      ["Satoru Gojo", "venda"],
      ["Sukuna", "dedos"],
      ["Geto", "manipulação"],
      ["Yuta Okkotsu", "promessa"],
      ["Maki Zenin", "arma"],
      ["Panda", "núcleo"],
      ["Toge Inumaki", "ingredientes"],
      ["Nanami", "gravata"],
      ["Mahito", "alma"],
      ["Jogo", "vulcão"],
      ["Hanami", "floresta"],
      ["Toji Fushiguro", "restrição"],
      ["Shoko", "autópsia"],
      ["Todo", "ídolo"],
      ["Choso", "irmandade"],
      ["Kenjaku", "cérebro"],
      ["Rika", "anel"],
      ["Shibuya", "caos"],
      ["Colégio Tóquio", "alunos"],
      ["Domínio", "barreira"],
      ["Energia amaldiçoada", "fluxo"],
      ["Black Flash", "impacto"],
      ["Shikigami", "invocação"],
      ["Mahoraga", "roda"],
      ["Vazio infinito", "paralisia"],
      ["Santuário malevolente", "altar"],
      ["Boogie Woogie", "palma"],
      ["Dez Sombras", "família"],
      ["Purple", "aniquilação"],
      ["Finger", "relíquia"],
      ["Exorcismo", "ritual"],
      ["Vaso", "recipiente"],
      ["Selo", "prisão"],
      ["Prison Realm", "cubos"],
      ["Culling Game", "colônia"],
      ["Grau especial", "elite"],
      ["Kashimo", "tempestade"],
    ]),
  },
  {
    key: "demon-slayer",
    title: "Demon Slayer",
    icon: "katana",
    mode: "word",
    items: buildWordItems([
      ["Tanjiro", "olfato"],
      ["Nezuko", "caixa"],
      ["Zenitsu", "sono"],
      ["Inosuke", "javali"],
      ["Giyu", "serenidade"],
      ["Shinobu", "veneno"],
      ["Rengoku", "chamas"],
      ["Tengen", "extravagância"],
      ["Mitsuri", "paixão"],
      ["Muichiro", "névoa"],
      ["Obanai", "serpente"],
      ["Sanemi", "cicatriz"],
      ["Gyomei", "rosário"],
      ["Kanao", "moeda"],
      ["Genya", "espingarda"],
      ["Muzan", "chapéu"],
      ["Akaza", "combate"],
      ["Daki", "faixa"],
      ["Gyutaro", "foice"],
      ["Enmu", "trem"],
      ["Rui", "teia"],
      ["Tamayo", "pesquisa"],
      ["Kagaya", "liderança"],
      ["Hashira", "pilar"],
      ["Nichirin", "sol"],
      ["Respiração da Água", "fluxo"],
      ["Respiração do Fogo", "ardor"],
      ["Respiração do Trovão", "relâmpago"],
      ["Respiração da Besta", "instinto"],
      ["Castelo Infinito", "labirinto"],
      ["Lua Superior", "hierarquia"],
      ["Lua Inferior", "submissão"],
      ["Demônio", "presa"],
      ["Caçador", "uniforme"],
      ["Glicínia", "repelente"],
      ["Trem Infinito", "vagão"],
      ["Distrito do Entretenimento", "neon"],
      ["Yoriichi", "marca"],
      ["Kokushibo", "seis"],
      ["Douma", "leque"],
    ]),
  },
  {
    key: "friends",
    title: "Friends",
    icon: "coffee",
    mode: "word",
    items: buildWordItems([
      ["Rachel", "moda"],
      ["Ross", "dinossauro"],
      ["Monica", "competição"],
      ["Chandler", "sarcasmo"],
      ["Joey", "audição"],
      ["Phoebe", "violão"],
      ["Gunther", "cafeteria"],
      ["Janice", "risada"],
      ["Mike", "piano"],
      ["Richard", "bigode"],
      ["Carol", "divórcio"],
      ["Susan", "debate"],
      ["Ben", "fantasia"],
      ["Emma", "bebê"],
      ["Central Perk", "sofá"],
      ["Apartamento 20", "roxo"],
      ["Apartamento 19", "cadeira"],
      ["Sofá", "laranja"],
      ["Café", "caneca"],
      ["Pivot", "escada"],
      ["Lobster", "alma"],
      ["Smelly Cat", "música"],
      ["Unagi", "alerta"],
      ["Armadillo", "natal"],
      ["Cabeça de peru", "feriado"],
      ["Vídeo do baile", "saudade"],
      ["Geller Cup", "troféu"],
      ["How you doin", "cantada"],
      ["Regina Phalange", "disfarce"],
      ["Sanduíche", "sobras"],
      ["Thanksgiving", "forno"],
      ["Las Vegas", "capela"],
      ["Londres", "chuva"],
      ["Trigêmeos", "fraldas"],
      ["Massagem", "cliente"],
      ["Moda", "passarela"],
      ["Paleontologia", "fóssil"],
      ["Chef", "receita"],
      ["Ator", "teste"],
      ["Foosball", "mesa"],
    ]),
  },
  {
    key: "clash",
    title: "Clash",
    icon: "shield",
    mode: "word",
    items: buildWordItems([
      ["Bárbaro", "espada"],
      ["Arqueira", "alcance"],
      ["Gigante", "torre"],
      ["Mago", "splash"],
      ["P.E.K.K.A", "armadura"],
      ["Mini P.E.K.K.A", "pancada"],
      ["Príncipe", "carga"],
      ["Princesa", "ponte"],
      ["Bruxa", "esqueletos"],
      ["Corredor", "porco"],
      ["Mosqueteira", "rifle"],
      ["Valquíria", "giro"],
      ["Lava Hound", "filhotes"],
      ["Balão", "bomba"],
      ["Goblin", "adaga"],
      ["Cavaleiro", "bigode"],
      ["Mineiro", "broca"],
      ["Bandida", "dash"],
      ["Lenhador", "fúria"],
      ["Fantasma Real", "invisível"],
      ["Monge", "reflexo"],
      ["Rainha Arqueira", "camuflagem"],
      ["Rei Esqueleto", "invocação"],
      ["Torre Inferno", "feixe"],
      ["Tesla", "choque"],
      ["Canhão", "defesa"],
      ["Fornalha", "forja"],
      ["Torre de Bombas", "barreira"],
      ["X-Besta", "cerco"],
      ["Morteiro", "curva"],
      ["Espelho", "duplicar"],
      ["Zap", "reinício"],
      ["Bola de Fogo", "pressão"],
      ["Flechas", "dispersão"],
      ["Tronco", "empurrão"],
      ["Veneno", "dano"],
      ["Relâmpago", "estouro"],
      ["Congelamento", "travamento"],
      ["Elixir", "recurso"],
      ["Baú", "recompensa"],
    ]),
  },
];

assertDefaultWordPacks(DEFAULT_WORD_PACKS);
