export type DefaultWordPackDefinition = {
  key: string;
  title: string;
  icon: string;
  mode: "word";
  hint: string;
  items: string[];
};

export type DefaultQuestionPackDefinition = {
  key: string;
  title: string;
  icon: string;
  mode: "question";
  items: Array<{
    question: string;
    impostorQuestion: string;
  }>;
};

export const DEFAULT_WORD_PACKS: DefaultWordPackDefinition[] = [
  {
    key: "classico",
    title: "Classico",
    icon: "star",
    mode: "word",
    hint: "cotidiano",
    items: [
      "Pizza", "Praia", "Celular", "Cinema", "Cachorro", "Churrasco", "Bicicleta", "Geladeira", "Futebol", "Sorvete",
      "Aviao", "Livraria", "Hospital", "Computador", "Relogio", "Chocolate", "Parque", "Professor", "Cama", "Cafeteria",
      "Montanha", "Supermercado", "Viagem", "Violao", "Lasanha", "Aeroporto", "Espelho", "Abacaxi", "Museu", "Bolo",
      "Onibus", "Jaqueta", "Teatro", "Pipoca", "Escola", "Gato", "Papel", "Caneta", "Vento", "Castelo",
      "Piscina", "Sanduiche", "Telefone", "Janela", "RodaGigante", "Cozinha", "Astronauta", "Farmacia", "Bateria", "Lancheira",
      "Ponte", "Acampamento", "Sofa", "Caderno", "Padaria", "Dinossauro", "Sapato", "Arvore", "Copo", "Trem",
    ],
  },
  {
    key: "futebol",
    title: "Futebol",
    icon: "football",
    mode: "word",
    hint: "esporte",
    items: [
      "Bola", "Trave", "Rede", "Escanteio", "Falta", "Penalti", "Camisa10", "Zagueiro", "Goleiro", "Lateral",
      "Centroavante", "Meia", "Volante", "Artilheiro", "Capitao", "Chuteira", "VAR", "Torcida", "Bandeirinha", "CartaoAmarelo",
      "CartaoVermelho", "Golaco", "Drible", "Caneta", "Chapeu", "Cabecada", "Assistencia", "Classico", "Derbi", "Final",
      "Libertadores", "CopaDoMundo", "Maracana", "Bernabeu", "CampNou", "PremierLeague", "Brasileirao", "Champions", "Flamengo", "Corinthians",
      "Palmeiras", "Santos", "SaoPaulo", "Barcelona", "RealMadrid", "Messi", "CristianoRonaldo", "Neymar", "Mbappe", "Haaland",
      "Ancelotti", "Tite", "Selecao", "Impedimento", "ContraAtaque", "Tabela", "Cobertura", "BicicletaNoAr", "TorcidaOrganizada", "Catimba",
    ],
  },
  {
    key: "area-da-saude",
    title: "Area da Saude",
    icon: "health",
    mode: "word",
    hint: "cuidado",
    items: [
      "Hospital", "Clinica", "Medico", "Enfermeiro", "Dentista", "Cirurgia", "Vacina", "Receita", "Estetoscopio", "Prontuario",
      "RaioX", "Ultrassom", "Ambulancia", "Curativo", "Seringa", "Termometro", "Pressao", "Diagnostico", "Sintoma", "Febre",
      "Dor", "Gripe", "Resfriado", "Farmacia", "Remedio", "Injecao", "Exame", "Consulta", "UTI", "Plantao",
      "Fisioterapia", "Psicologo", "Nutricionista", "Cardiologista", "Pediatra", "Neurologista", "Ortopedista", "Hemograma", "Sangue", "Pulso",
      "Anatomia", "Epidemia", "SaudeMental", "ProntoSocorro", "Leito", "Mascara", "Luva", "Anestesista", "Bisturi", "Reabilitacao",
      "Infeccao", "Triagem", "Emergencia", "Respiracao", "Tomografia", "Microscopio", "Laboratorio", "Bacteria", "Virus", "Imunidade",
    ],
  },
  {
    key: "tecnologia",
    title: "Tecnologia",
    icon: "laptop",
    mode: "word",
    hint: "digital",
    items: [
      "Notebook", "Celular", "Tablet", "Processador", "MemoriaRAM", "Monitor", "Teclado", "Mouse", "PlacaMae", "Servidor",
      "Nuvem", "BancoDeDados", "Algoritmo", "Codigo", "Deploy", "Bug", "Firewall", "Bluetooth", "WiFi", "Aplicativo",
      "SistemaOperacional", "Android", "iOS", "Windows", "Linux", "Macbook", "Console", "Controle", "Streaming", "Podcast",
      "InteligenciaArtificial", "MachineLearning", "Robotica", "Drone", "Impressora3D", "USB", "HDMI", "SSD", "Backup", "Senha",
      "Biometria", "Criptografia", "Chatbot", "Navegador", "Frontend", "Backend", "API", "Framework", "Git", "Repositorio",
      "Cursor", "Pixel", "DesignSystem", "Automacao", "Sensor", "Chip", "Compilador", "Terminal", "Kernel", "Script",
    ],
  },
  {
    key: "disney",
    title: "Disney",
    icon: "castle",
    mode: "word",
    hint: "animacao",
    items: [
      "Mickey", "Minnie", "Donald", "Pateta", "Pluto", "TioPatinhas", "Cinderela", "Bela", "Aurora", "BrancaDeNeve",
      "Rapunzel", "Ariel", "Moana", "Mulan", "Jasmine", "Pocahontas", "Elsa", "Anna", "Olaf", "Simba",
      "Mufasa", "Scar", "Nala", "Timon", "Pumba", "Aladdin", "Genio", "Jafar", "Alicia", "PeterPan",
      "Sininho", "Wendy", "Lilo", "Stitch", "Hercules", "Megara", "Tarzan", "Jane", "Dumbo", "Bambi",
      "Pinocchio", "Cruella", "Malefica", "Ursula", "Encanto", "Mirabel", "Bruno", "Madrigal", "Frozen", "ToyStory",
      "Woody", "BuzzLightyear", "Ratatouille", "WallE", "Up", "MonstrosSA", "Nemo", "Dory", "Zootopia", "DivertidaMente",
    ],
  },
  {
    key: "harry-potter",
    title: "Harry Potter",
    icon: "bolt",
    mode: "word",
    hint: "magia",
    items: [
      "Harry", "Hermione", "Ron", "Hogwarts", "Dumbledore", "Snape", "Voldemort", "Hagrid", "Draco", "Sirius",
      "Lupin", "Bellatrix", "Cedric", "Luna", "Neville", "Ginny", "Molly", "Arthur", "Fred", "George",
      "ChoChang", "McGonagall", "Filch", "Dobby", "Buckbeak", "Fawkes", "Hedwig", "Nimbus2000", "Quadribol", "BecoDiagonal",
      "Gringotes", "SalaPrecisa", "Azkaban", "Patrono", "Varinha", "Expelliarmus", "ExpectoPatronum", "AvadaKedavra", "Horcrux", "Penseira",
      "PedraFilosofal", "CapaDaInvisibilidade", "CaliceDeFogo", "CameraSecreta", "ReliquiasDaMorte", "Sonserina", "Grifinoria", "Corvinal", "LufaLufa", "Hogsmeade",
      "MinistroDaMagia", "Comensal", "Trasgo", "Basilisco", "Dementador", "PomoDeOuro", "ViraTempo", "ProfetaDiario", "MaraudersMap", "Horcux",
    ],
  },
  {
    key: "naruto",
    title: "Naruto",
    icon: "leaf",
    mode: "word",
    hint: "ninja",
    items: [
      "Naruto", "Sasuke", "Sakura", "Kakashi", "Hinata", "Neji", "RockLee", "Tenten", "Shikamaru", "Choji",
      "Ino", "Gaara", "Temari", "Kankuro", "Jiraiya", "Tsunade", "Orochimaru", "Itachi", "Kisame", "Pain",
      "Konan", "Madara", "Obito", "Minato", "Kushina", "Hashirama", "Tobirama", "Hiruzen", "Asuma", "Kurenai",
      "Anbu", "Akatsuki", "Rasengan", "Chidori", "Sharingan", "Byakugan", "Rinnegan", "Kyuubi", "Kurama", "Susanoo",
      "Amaterasu", "Chuunin", "Genin", "Jounin", "Konoha", "Suna", "Mizukage", "Hokage", "Shuriken", "Kunai",
      "Selo", "Ninjutsu", "Taijutsu", "Genjutsu", "Sannin", "Kabuto", "Deidara", "Sasori", "Hidan", "Zetsu",
    ],
  },
  {
    key: "valorant",
    title: "Valorant",
    icon: "target",
    mode: "word",
    hint: "tatica",
    items: [
      "Jett", "Phoenix", "Sage", "Brimstone", "Viper", "Sova", "Cypher", "Reyna", "Killjoy", "Breach",
      "Omen", "Astra", "Skye", "Yoru", "Chamber", "Neon", "Fade", "Harbor", "Gekko", "Deadlock",
      "Iso", "Clove", "Raze", "Classic", "Ghost", "Sheriff", "Vandal", "Phantom", "Bulldog", "Guardian",
      "Spectre", "Stinger", "Bucky", "Judge", "Operator", "Marshal", "Ares", "Odin", "Spike", "Eco",
      "Plant", "Defuse", "Headshot", "Ace", "Clutch", "Bind", "Haven", "Ascent", "Split", "Lotus",
      "Sunset", "Icebox", "Breeze", "Pearl", "Fracture", "Mid", "Smoke", "Flash", "Ult", "Retake",
    ],
  },
  {
    key: "league-of-legends",
    title: "League of Legends",
    icon: "swords",
    mode: "word",
    hint: "moba",
    items: [
      "Ahri", "Lux", "Garen", "Darius", "Jinx", "Vi", "Caitlyn", "Ashe", "Yasuo", "Yone",
      "LeeSin", "Zed", "Teemo", "Thresh", "Leona", "Katarina", "Akali", "Vayne", "Ezreal", "Morgana",
      "Aatrox", "Riven", "Sett", "Ekko", "Sylas", "Annie", "Nami", "Sona", "Braum", "Nautilus",
      "MasterYi", "Tryndamere", "Shaco", "Warwick", "Irelia", "Camille", "Fiora", "Kaisa", "Xayah", "Rakan",
      "Baron", "Dragao", "Arauto", "Nexus", "TopLane", "Jungle", "MidLane", "BotLane", "Support", "Gank",
      "Pentakill", "Farm", "Ward", "Smite", "Flash", "Ignite", "Teleport", "ARAM", "LCK", "Worlds",
    ],
  },
  {
    key: "minecraft",
    title: "Minecraft",
    icon: "pickaxe",
    mode: "word",
    hint: "blocos",
    items: [
      "Steve", "Alex", "Creeper", "Zombie", "Skeleton", "Enderman", "Villager", "IronGolem", "Wither", "Dragon",
      "Nether", "End", "Overworld", "Diamante", "Esmeralda", "Redstone", "Obsidiana", "Carvao", "Ferro", "Ouro",
      "Picareta", "Espada", "Machado", "Pa", "Enxada", "Fornalha", "Bau", "MesaDeTrabalho", "Bigorna", "Elitro",
      "Tocha", "Balde", "Agua", "Lava", "Portal", "Beacon", "Enchant", "Pocao", "Arco", "Besta",
      "Trilho", "Vagoes", "Aldeia", "Templo", "Mina", "Bedrock", "Tijolo", "Madeira", "Pedregulho", "Terra",
      "Farm", "Trigo", "Batata", "Cenoura", "Lobo", "Gato", "Panda", "Axolote", "Slime", "TNT",
    ],
  },
  {
    key: "one-piece",
    title: "One Piece",
    icon: "skull",
    mode: "word",
    hint: "pirata",
    items: [
      "Luffy", "Zoro", "Nami", "Usopp", "Sanji", "Chopper", "Robin", "Franky", "Brook", "Jinbe",
      "Shanks", "Ace", "Sabo", "Law", "Kid", "Buggy", "Crocodile", "Mihawk", "Kaido", "BigMom",
      "Doflamingo", "Teach", "BarbaBranca", "Oden", "Yamato", "Momonosuke", "Vivi", "Smoker", "Koby", "Helmeppo",
      "Marinha", "Almirante", "Yonko", "Shichibukai", "GrandLine", "RedLine", "LaughTale", "Poneglyph", "Haki", "GearFourth",
      "GomuGomu", "MeraMera", "OpeOpe", "BaraBara", "GuraGura", "Sunny", "GoingMerry", "Wano", "Dressrosa", "Alabasta",
      "Skypiea", "Water7", "EniesLobby", "Marineford", "ImpelDown", "BinksSake", "DenDenMushi", "BusterCall", "AkumaNoMi", "Mugiwara",
    ],
  },
  {
    key: "fortnite",
    title: "Fortnite",
    icon: "blaster",
    mode: "word",
    hint: "battle royale",
    items: [
      "BattleBus", "VictoryRoyale", "Build", "Storm", "Loot", "Chest", "Shield", "Slurp", "Pickaxe", "Glider",
      "BattlePass", "TiltedTowers", "PleasantPark", "RetailRow", "SaltySprings", "LootLake", "DustyDepot", "FrenzyFarm", "LazyLake", "MegaCity",
      "Jonesy", "Peely", "Fishstick", "Raven", "Midas", "Drift", "Meowscles", "Aura", "Lynx", "SkullTrooper",
      "PumpShotgun", "TacShotgun", "Scar", "SMG", "Sniper", "RocketLauncher", "BoogieBomb", "ChugJug", "Medkit", "Bandage",
      "RebootVan", "Crown", "Emote", "DefaultDance", "Squad", "Duos", "Solos", "NoBuild", "Arena", "Cranked",
      "Drop", "Zone", "StormSurge", "SupplyDrop", "LaunchPad", "PortAFort", "SlurpJuice", "Shockwave", "Rift", "BusDriver",
    ],
  },
  {
    key: "pokemon",
    title: "Pokemon",
    icon: "pokeball",
    mode: "word",
    hint: "criatura",
    items: [
      "Pikachu", "Charmander", "Bulbasaur", "Squirtle", "Eevee", "Snorlax", "Mewtwo", "Mew", "Gengar", "Lapras",
      "Jigglypuff", "Psyduck", "Magikarp", "Gyarados", "Onix", "Geodude", "Machamp", "Dragonite", "Vulpix", "Growlithe",
      "Arcanine", "Abra", "Alakazam", "Gastly", "Haunter", "Ditto", "Pidgeot", "Rattata", "Caterpie", "Butterfree",
      "Charizard", "Blastoise", "Venusaur", "Lucario", "Greninja", "Gardevoir", "Sylveon", "Umbreon", "Espeon", "Tyranitar",
      "Pokebola", "Pokedex", "Ginasio", "Treinador", "ProfessorOak", "EquipeRocket", "Ash", "Misty", "Brock", "Jesse",
      "James", "Meowth", "LigaPokemon", "Kanto", "Johto", "Hoenn", "Sinnoh", "Unova", "Kalos", "Paldea",
    ],
  },
  {
    key: "star-wars",
    title: "Star Wars",
    icon: "lightsaber",
    mode: "word",
    hint: "galaxia",
    items: [
      "Luke", "Leia", "HanSolo", "Chewbacca", "DarthVader", "ObiWan", "Yoda", "Anakin", "Padme", "Palpatine",
      "R2D2", "C3PO", "BobaFett", "JangoFett", "Ahsoka", "Thrawn", "Mandalorian", "Grogu", "Rey", "Finn",
      "Poe", "KyloRen", "BB8", "MaceWindu", "QuiGon", "Dooku", "Grievous", "JarJar", "Lando", "Jabba",
      "MillenniumFalcon", "XWing", "TieFighter", "Destroyer", "EstrelaDaMorte", "SabreDeLuz", "Forca", "Jedi", "Sith", "Clone",
      "Stormtrooper", "Tatooine", "Coruscant", "Naboo", "Hoth", "Dagobah", "Endor", "Mustafar", "Alderaan", "Cantina",
      "Holocron", "Podracer", "Mandalore", "AlaRebelde", "Imperio", "Resistencia", "Ordem66", "Senado", "Galaxia", "Blaster",
    ],
  },
  {
    key: "game-of-thrones",
    title: "Game of Thrones",
    icon: "crown",
    mode: "word",
    hint: "reino",
    items: [
      "JonSnow", "Daenerys", "Tyrion", "Arya", "Sansa", "Bran", "NedStark", "Cersei", "Jaime", "Joffrey",
      "Theon", "Brienne", "Samwell", "Davos", "Melisandre", "Bronn", "Hound", "Mountain", "Tywin", "Robb",
      "Catelyn", "KhalDrogo", "Missandei", "GreyWorm", "Varys", "Baelish", "Ramsay", "Tormund", "Ygritte", "Viserys",
      "Winterfell", "KingLanding", "Dragonstone", "TheWall", "IronThrone", "Dothraki", "Unsullied", "Wildling", "WhiteWalker", "NightKing",
      "Raven", "ValyrianSteel", "Direwolf", "HouseStark", "HouseLannister", "HouseTargaryen", "HouseBaratheon", "HouseGreyjoy", "HouseTyrell", "HouseMartell",
      "Hodor", "RedWedding", "Blackwater", "LongNight", "SmallCouncil", "Citadel", "Maester", "Westeros", "Essos", "Dragon",
    ],
  },
  {
    key: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    icon: "fist",
    mode: "word",
    hint: "feitico",
    items: [
      "Yuji", "Megumi", "Nobara", "Gojo", "Sukuna", "Geto", "Yuta", "Maki", "Panda", "Toge",
      "Nanami", "Mahito", "Jogo", "Hanami", "Dagon", "Toji", "Shoko", "Utahime", "MeiMei", "Todo",
      "Choso", "Naobito", "Kashimo", "Higuruma", "Hakari", "Kenjaku", "Rika", "Shibuya", "TokyoJujutsu", "KyotoJujutsu",
      "Dominio", "EnergiaAmaldicoada", "BlackFlash", "Shikigami", "Mahoraga", "UnlimitedVoid", "MalevolentShrine", "BoogieWoogie", "TenShadows", "Red",
      "Blue", "Purple", "Finger", "Curse", "Exorcismo", "Vaso", "Selo", "PrisonRealm", "CullingGame", "SpecialGrade",
      "Grade1", "HeavenlyRestriction", "Satoru", "Fushiguro", "Kugisaki", "AoiTodo", "StarPlasma", "Miguel", "Uraume", "SukunaVessel",
    ],
  },
  {
    key: "demon-slayer",
    title: "Demon Slayer",
    icon: "katana",
    mode: "word",
    hint: "oni",
    items: [
      "Tanjiro", "Nezuko", "Zenitsu", "Inosuke", "Giyu", "Shinobu", "Rengoku", "Tengen", "Mitsuri", "Muichiro",
      "Obanai", "Sanemi", "Gyomei", "Kanao", "Genya", "Muzan", "Akaza", "Daki", "Gyutaro", "Enmu",
      "Rui", "Tamayo", "Yushiro", "Kagaya", "Aoi", "Urokodaki", "Sabito", "Makomo", "Hashira", "Corvo",
      "Nichirin", "RespiracaoDaAgua", "RespiracaoDoFogo", "RespiracaoDoTrovao", "RespiracaoDaBesta", "RespiracaoDoSom", "RespiracaoDoAmor", "RespiracaoDaSerpente", "RespiracaoDoVento", "RespiracaoDaRocha",
      "CasteloInfinito", "LuaSuperior", "LuaInferior", "Demonio", "Cacador", "Glicinia", "Treinamento", "MarcaDoCacador", "HinokamiKagura", "TremInfinito",
      "DistritoDoEntretenimento", "AldeiaDosFerreiros", "Katana", "Oni", "KasugaiCrow", "Yoriichi", "Kokushibo", "Douma", "Hantengu", "Nakime",
    ],
  },
  {
    key: "friends",
    title: "Friends",
    icon: "coffee",
    mode: "word",
    hint: "sitcom",
    items: [
      "Rachel", "Ross", "Monica", "Chandler", "Joey", "Phoebe", "Gunther", "Janice", "Mike", "Richard",
      "Carol", "Susan", "Ben", "Emma", "Tag", "Emily", "Paul", "Judy", "Jack", "Ursula",
      "CentralPerk", "Apt20", "Apt19", "Couch", "Coffee", "Pivot", "Lobster", "SmellyCat", "Unagi", "HolidayArmadillo",
      "TurkeyHead", "WeddingDress", "PromVideo", "GellerCup", "HowYouDoin", "WeWereOnABreak", "CouldIBew", "ReginaPhalange", "JoeySpecial", "Sandwich",
      "Thanksgiving", "LasVegas", "London", "Wedding", "Triplets", "Massage", "Fashion", "Paleontology", "Chef", "Actor",
      "BananaHammock", "Foosball", "Duck", "Chick", "Notebook", "SprayTan", "QuizGame", "Caboose", "Monana", "PrincessConsuela",
    ],
  },
  {
    key: "clash",
    title: "Clash",
    icon: "shield",
    mode: "word",
    hint: "estrategia",
    items: [
      "Barbaro", "Arqueira", "Gigante", "Mago", "Pekka", "MiniPekka", "Principe", "Princesa", "MagoEletrico", "Bruxa",
      "Corredor", "Mosqueteira", "Valquiria", "LavaHound", "Balao", "Goblin", "GoblinGigante", "BarrilDeGoblin", "Cavaleiro", "ArqueiroMagico",
      "Mineiro", "Bandida", "Lenhador", "FantasmaReal", "Monge", "CampeaoDourado", "RainhaArqueira", "ReiEsqueleto", "TorreInferno", "Tesla",
      "Canhao", "Fornalha", "CabanaDeGoblins", "CabanaDeBarbaros", "TorreDeBombas", "TorreDeFlechas", "XBow", "Morteiro", "Espelho", "Zap",
      "BolaDeFogo", "Flechas", "Tronco", "Veneno", "Relampago", "Congelamento", "Furia", "Clonagem", "Terremoto", "BarrilDeEsqueletos",
      "ClashRoyale", "ClashOfClans", "TownHall", "Arena", "Elixir", "Coroa", "Bau", "ClanWar", "Esqueletos", "Executor",
    ],
  },
];

export const DEFAULT_QUESTION_PACKS: DefaultQuestionPackDefinition[] = [
  {
    key: "classico",
    title: "Perguntas Classicas",
    icon: "star",
    mode: "question",
    items: [
      { question: "Qual comida voce comeria todo fim de semana?", impostorQuestion: "Qual comida voce evitaria todo fim de semana?" },
      { question: "Que lugar combina com um encontro tranquilo?", impostorQuestion: "Que lugar combina com uma festa caotica?" },
      { question: "Qual habito melhora seu dia?", impostorQuestion: "Qual habito atrapalha seu dia?" },
      { question: "Que objeto sempre salva uma viagem?", impostorQuestion: "Que objeto sempre fica esquecido na viagem?" },
      { question: "Qual filme voce veria de novo no cinema?", impostorQuestion: "Qual filme voce abandonaria na metade?" },
      { question: "Qual materia rende uma boa conversa?", impostorQuestion: "Qual materia rende um bocejo imediato?" },
      { question: "Que som combina com paz?", impostorQuestion: "Que som combina com bagunca?" },
      { question: "Qual lanche tem cara de madrugada?", impostorQuestion: "Qual lanche tem cara de cafe da manha?" },
      { question: "Que tarefa voce faz rapido?", impostorQuestion: "Que tarefa voce sempre adia?" },
      { question: "Qual lugar da cidade merece foto?", impostorQuestion: "Qual lugar da cidade merece ser evitado?" },
      { question: "Que personagem seria um bom colega de quarto?", impostorQuestion: "Que personagem seria um pessimo colega de quarto?" },
      { question: "Qual transporte combina com aventura?", impostorQuestion: "Qual transporte combina com conforto?" },
      { question: "Que cheiro lembra infancia?", impostorQuestion: "Que cheiro lembra correria?" },
      { question: "Qual sobremesa tem cara de festa?", impostorQuestion: "Qual sobremesa tem cara de cafe da tarde?" },
      { question: "Que qualidade deixa alguem confiavel?", impostorQuestion: "Que qualidade deixa alguem marcante?" },
      { question: "Qual app voce abriria primeiro no celular?", impostorQuestion: "Qual app voce apagaria primeiro do celular?" },
      { question: "Que roupa combina com ferias?", impostorQuestion: "Que roupa combina com trabalho?" },
      { question: "Qual animal parece mais simpatico?", impostorQuestion: "Qual animal parece mais assustador?" },
      { question: "Que clima combina com descansar?", impostorQuestion: "Que clima combina com se desafiar?" },
      { question: "Qual presente e facil de agradar?", impostorQuestion: "Qual presente e facil de errar?" },
      { question: "Que bebida combina com calor?", impostorQuestion: "Que bebida combina com frio?" },
      { question: "Qual jogo junta todo mundo?", impostorQuestion: "Qual jogo separa opinioes?" },
      { question: "Que lugar combina com domingo?", impostorQuestion: "Que lugar combina com sexta a noite?" },
      { question: "Qual profissao parece divertida?", impostorQuestion: "Qual profissao parece estressante?" },
      { question: "Que cor combina com energia?", impostorQuestion: "Que cor combina com calma?" },
      { question: "Qual serie rende maratona?", impostorQuestion: "Qual serie rende sono?" },
      { question: "Que fruta voce levaria para um piquenique?", impostorQuestion: "Que fruta voce evitaria num piquenique?" },
      { question: "Qual lugar tem cara de silencio?", impostorQuestion: "Qual lugar tem cara de barulho?" },
      { question: "Que superpoder facilitaria sua rotina?", impostorQuestion: "Que superpoder baguncaria sua rotina?" },
      { question: "Qual brinquedo merece voltar a moda?", impostorQuestion: "Qual brinquedo merece ficar no passado?" },
      { question: "Que musica combina com estrada?", impostorQuestion: "Que musica combina com treino?" },
      { question: "Qual doce some mais rapido da mesa?", impostorQuestion: "Qual doce sobra na mesa?" },
      { question: "Que item nao pode faltar no escritorio?", impostorQuestion: "Que item nao pode faltar na cozinha?" },
      { question: "Qual celebridade parece boa de papo?", impostorQuestion: "Qual celebridade parece dificil de lidar?" },
      { question: "Que cena pede aplauso?", impostorQuestion: "Que cena pede spoiler?" },
      { question: "Qual lugar do mundo voce visitaria primeiro?", impostorQuestion: "Qual lugar do mundo voce deixaria por ultimo?" },
      { question: "Que sabor combina com sorvete?", impostorQuestion: "Que sabor combina com sopa?" },
      { question: "Qual esporte rende mais historia?", impostorQuestion: "Qual esporte rende mais silencio?" },
      { question: "Que palavra descreve um bom lider?", impostorQuestion: "Que palavra descreve um bom entertainer?" },
      { question: "Qual tarefa domestica e menos pior?", impostorQuestion: "Qual tarefa domestica e mais chata?" },
      { question: "Que lugar combina com um pedido importante?", impostorQuestion: "Que lugar combina com uma despedida?" },
      { question: "Qual objeto tem cara de nostalgia?", impostorQuestion: "Qual objeto tem cara de futuro?" },
      { question: "Que personagem seria um bom professor?", impostorQuestion: "Que personagem seria um bom vilao?" },
      { question: "Qual app faria falta numa viagem?", impostorQuestion: "Qual app faria falta num estudo?" },
      { question: "Que bebida voce pediria num encontro?", impostorQuestion: "Que bebida voce pediria depois de um treino?" },
      { question: "Qual comida combina com chuva?", impostorQuestion: "Qual comida combina com praia?" },
      { question: "Que lugar pede roupa confortavel?", impostorQuestion: "Que lugar pede roupa elegante?" },
      { question: "Qual talento seria util no dia a dia?", impostorQuestion: "Qual talento seria util numa aventura?" },
      { question: "Qual filme combina com amigos?", impostorQuestion: "Qual filme combina com assistir sozinho?" },
      { question: "Que premio voce gostaria de ganhar?", impostorQuestion: "Que premio voce gostaria de entregar?" },
      { question: "Qual decisao voce toma rapido?", impostorQuestion: "Qual decisao voce enrola para tomar?" },
      { question: "Que lembranca merece foto?", impostorQuestion: "Que lembranca merece diario?" },
      { question: "Qual lugar da casa e mais acolhedor?", impostorQuestion: "Qual lugar da casa e mais utilitario?" },
      { question: "Que refeicao tem cara de celebracao?", impostorQuestion: "Que refeicao tem cara de rotina?" },
      { question: "Qual hobby aproxima pessoas?", impostorQuestion: "Qual hobby isola pessoas?" },
      { question: "Que compra vale cada centavo?", impostorQuestion: "Que compra arrepende rapido?" },
      { question: "Qual momento do dia parece mais leve?", impostorQuestion: "Qual momento do dia parece mais intenso?" },
      { question: "Que qualidade faz um time funcionar?", impostorQuestion: "Que qualidade faz um artista brilhar?" },
      { question: "Qual objeto deixa sua mesa melhor?", impostorQuestion: "Qual objeto deixa sua mochila melhor?" },
      { question: "Que viagem rende boas historias?", impostorQuestion: "Que viagem rende bons descansos?" },
    ],
  },
  {
    key: "entretenimento",
    title: "Perguntas de Entretenimento",
    icon: "sparkles",
    mode: "question",
    items: [
      { question: "Qual personagem merece um spin off?", impostorQuestion: "Qual personagem merece ficar no misterio?" },
      { question: "Que serie voce recomendaria de olhos fechados?", impostorQuestion: "Que serie voce recomendaria so pelo caos?" },
      { question: "Qual desenho tem trilha sonora marcante?", impostorQuestion: "Qual desenho tem visual marcante?" },
      { question: "Que filme merece sequencia?", impostorQuestion: "Que filme deveria ter parado no primeiro?" },
      { question: "Qual vilao rouba a cena?", impostorQuestion: "Qual heroi rouba a cena?" },
      { question: "Que saga rende maratona de fim de semana?", impostorQuestion: "Que saga rende conversa de bar?" },
      { question: "Qual reality renderia boa estrategia?", impostorQuestion: "Qual reality renderia boas fofocas?" },
      { question: "Que musica faz todo mundo cantar junto?", impostorQuestion: "Que musica faz todo mundo dancar junto?" },
      { question: "Qual ator combina com comedia?", impostorQuestion: "Qual ator combina com suspense?" },
      { question: "Que jogo rende rivalidade saudavel?", impostorQuestion: "Que jogo rende cooperacao total?" },
      { question: "Qual personagem parece um bom lider?", impostorQuestion: "Qual personagem parece um bom parceiro de confusao?" },
      { question: "Que final de obra divide opinioes?", impostorQuestion: "Que final de obra une opinioes?" },
    ],
  },
  {
    key: "rotina",
    title: "Perguntas de Rotina",
    icon: "clock",
    mode: "question",
    items: [
      { question: "O que voce faz logo ao acordar?", impostorQuestion: "O que voce faz logo antes de dormir?" },
      { question: "Que tarefa voce resolve cedo?", impostorQuestion: "Que tarefa voce empurra ate tarde?" },
      { question: "Qual item mora na sua mochila?", impostorQuestion: "Qual item mora na sua mesa?" },
      { question: "Que refeicao organiza seu dia?", impostorQuestion: "Que refeicao fecha seu dia?" },
      { question: "Qual momento pede silencio?", impostorQuestion: "Qual momento pede companhia?" },
      { question: "Que notificacao voce abre na hora?", impostorQuestion: "Que notificacao voce ignora na hora?" },
      { question: "Qual habito parece pequeno mas ajuda muito?", impostorQuestion: "Qual habito parece pequeno mas atrapalha muito?" },
      { question: "Que lugar da cidade faz parte da sua semana?", impostorQuestion: "Que lugar da cidade faz parte do seu fim de semana?" },
      { question: "Qual roupa voce repete sem culpa?", impostorQuestion: "Qual roupa voce guarda para ocasioes especiais?" },
      { question: "Que som costuma acompanhar seu trabalho?", impostorQuestion: "Que som costuma acompanhar seu descanso?" },
      { question: "Qual app agiliza sua vida?", impostorQuestion: "Qual app consome seu tempo?" },
      { question: "Que decisao diaria voce toma no automatico?", impostorQuestion: "Que decisao diaria voce repensa demais?" },
    ],
  },
];
