export {
  DEFAULT_WORD_PACKS,
  type DefaultWordPackDefinition,
} from "./defaultWordPacks.js";

export type DefaultQuestionPackDefinition = {
  key: string;
  title: string;
  icon: string;
  mode: "question";
  items: Array<{
    question: string;
    impostorQuestion: string;
  }>;
};

export const DEFAULT_QUESTION_PACKS: DefaultQuestionPackDefinition[] = [
  {
    key: "classico",
    title: "Perguntas Classicas",
    icon: "star",
    mode: "question",
    items: [
      { question: "Qual comida voce comeria todo fim de semana?", impostorQuestion: "Qual comida voce evitaria todo fim de semana?" },
      { question: "Que lugar combina com um encontro tranquilo?", impostorQuestion: "Que lugar combina com uma festa caotica?" },
      { question: "Qual habito melhora seu dia?", impostorQuestion: "Qual habito atrapalha seu dia?" },
      { question: "Que objeto sempre salva uma viagem?", impostorQuestion: "Que objeto sempre fica esquecido na viagem?" },
      { question: "Qual filme voce veria de novo no cinema?", impostorQuestion: "Qual filme voce abandonaria na metade?" },
      { question: "Qual materia rende uma boa conversa?", impostorQuestion: "Qual materia rende um bocejo imediato?" },
      { question: "Que som combina com paz?", impostorQuestion: "Que som combina com bagunca?" },
      { question: "Qual lanche tem cara de madrugada?", impostorQuestion: "Qual lanche tem cara de cafe da manha?" },
      { question: "Que tarefa voce faz rapido?", impostorQuestion: "Que tarefa voce sempre adia?" },
      { question: "Qual lugar da cidade merece foto?", impostorQuestion: "Qual lugar da cidade merece ser evitado?" },
      { question: "Que personagem seria um bom colega de quarto?", impostorQuestion: "Que personagem seria um pessimo colega de quarto?" },
      { question: "Qual transporte combina com aventura?", impostorQuestion: "Qual transporte combina com conforto?" },
      { question: "Que cheiro lembra infancia?", impostorQuestion: "Que cheiro lembra correria?" },
      { question: "Qual sobremesa tem cara de festa?", impostorQuestion: "Qual sobremesa tem cara de cafe da tarde?" },
      { question: "Que qualidade deixa alguem confiavel?", impostorQuestion: "Que qualidade deixa alguem marcante?" },
      { question: "Qual app voce abriria primeiro no celular?", impostorQuestion: "Qual app voce apagaria primeiro do celular?" },
      { question: "Que roupa combina com ferias?", impostorQuestion: "Que roupa combina com trabalho?" },
      { question: "Qual animal parece mais simpatico?", impostorQuestion: "Qual animal parece mais assustador?" },
      { question: "Que clima combina com descansar?", impostorQuestion: "Que clima combina com se desafiar?" },
      { question: "Qual presente e facil de agradar?", impostorQuestion: "Qual presente e facil de errar?" },
      { question: "Que bebida combina com calor?", impostorQuestion: "Que bebida combina com frio?" },
      { question: "Qual jogo junta todo mundo?", impostorQuestion: "Qual jogo separa opinioes?" },
      { question: "Que lugar combina com domingo?", impostorQuestion: "Que lugar combina com sexta a noite?" },
      { question: "Qual profissao parece divertida?", impostorQuestion: "Qual profissao parece estressante?" },
      { question: "Que cor combina com energia?", impostorQuestion: "Que cor combina com calma?" },
      { question: "Qual serie rende maratona?", impostorQuestion: "Qual serie rende sono?" },
      { question: "Que fruta voce levaria para um piquenique?", impostorQuestion: "Que fruta voce evitaria num piquenique?" },
      { question: "Qual lugar tem cara de silencio?", impostorQuestion: "Qual lugar tem cara de barulho?" },
      { question: "Que superpoder facilitaria sua rotina?", impostorQuestion: "Que superpoder baguncaria sua rotina?" },
      { question: "Qual brinquedo merece voltar a moda?", impostorQuestion: "Qual brinquedo merece ficar no passado?" },
      { question: "Que musica combina com estrada?", impostorQuestion: "Que musica combina com treino?" },
      { question: "Qual doce some mais rapido da mesa?", impostorQuestion: "Qual doce sobra na mesa?" },
      { question: "Que item nao pode faltar no escritorio?", impostorQuestion: "Que item nao pode faltar na cozinha?" },
      { question: "Qual celebridade parece boa de papo?", impostorQuestion: "Qual celebridade parece dificil de lidar?" },
      { question: "Que cena pede aplauso?", impostorQuestion: "Que cena pede spoiler?" },
      { question: "Qual lugar do mundo voce visitaria primeiro?", impostorQuestion: "Qual lugar do mundo voce deixaria por ultimo?" },
      { question: "Que sabor combina com sorvete?", impostorQuestion: "Que sabor combina com sopa?" },
      { question: "Qual esporte rende mais historia?", impostorQuestion: "Qual esporte rende mais silencio?" },
      { question: "Que palavra descreve um bom lider?", impostorQuestion: "Que palavra descreve um bom entertainer?" },
      { question: "Qual tarefa domestica e menos pior?", impostorQuestion: "Qual tarefa domestica e mais chata?" },
      { question: "Que lugar combina com um pedido importante?", impostorQuestion: "Que lugar combina com uma despedida?" },
      { question: "Qual objeto tem cara de nostalgia?", impostorQuestion: "Qual objeto tem cara de futuro?" },
      { question: "Que personagem seria um bom professor?", impostorQuestion: "Que personagem seria um bom vilao?" },
      { question: "Qual app faria falta numa viagem?", impostorQuestion: "Qual app faria falta num estudo?" },
      { question: "Que bebida voce pediria num encontro?", impostorQuestion: "Que bebida voce pediria depois de um treino?" },
      { question: "Qual comida combina com chuva?", impostorQuestion: "Qual comida combina com praia?" },
      { question: "Que lugar pede roupa confortavel?", impostorQuestion: "Que lugar pede roupa elegante?" },
      { question: "Qual talento seria util no dia a dia?", impostorQuestion: "Qual talento seria util numa aventura?" },
      { question: "Qual filme combina com amigos?", impostorQuestion: "Qual filme combina com assistir sozinho?" },
      { question: "Que premio voce gostaria de ganhar?", impostorQuestion: "Que premio voce gostaria de entregar?" },
      { question: "Qual decisao voce toma rapido?", impostorQuestion: "Qual decisao voce enrola para tomar?" },
      { question: "Que lembranca merece foto?", impostorQuestion: "Que lembranca merece diario?" },
      { question: "Qual lugar da casa e mais acolhedor?", impostorQuestion: "Qual lugar da casa e mais utilitario?" },
      { question: "Que refeicao tem cara de celebracao?", impostorQuestion: "Que refeicao tem cara de rotina?" },
      { question: "Qual hobby aproxima pessoas?", impostorQuestion: "Qual hobby isola pessoas?" },
      { question: "Que compra vale cada centavo?", impostorQuestion: "Que compra arrepende rapido?" },
      { question: "Qual momento do dia parece mais leve?", impostorQuestion: "Qual momento do dia parece mais intenso?" },
      { question: "Que qualidade faz um time funcionar?", impostorQuestion: "Que qualidade faz um artista brilhar?" },
      { question: "Qual objeto deixa sua mesa melhor?", impostorQuestion: "Qual objeto deixa sua mochila melhor?" },
      { question: "Que viagem rende boas historias?", impostorQuestion: "Que viagem rende bons descansos?" },
    ],
  },
  {
    key: "entretenimento",
    title: "Perguntas de Entretenimento",
    icon: "sparkles",
    mode: "question",
    items: [
      { question: "Qual personagem merece um spin off?", impostorQuestion: "Qual personagem merece ficar no misterio?" },
      { question: "Que serie voce recomendaria de olhos fechados?", impostorQuestion: "Que serie voce recomendaria so pelo caos?" },
      { question: "Qual desenho tem trilha sonora marcante?", impostorQuestion: "Qual desenho tem visual marcante?" },
      { question: "Que filme merece sequencia?", impostorQuestion: "Que filme deveria ter parado no primeiro?" },
      { question: "Qual vilao rouba a cena?", impostorQuestion: "Qual heroi rouba a cena?" },
      { question: "Que saga rende maratona de fim de semana?", impostorQuestion: "Que saga rende conversa de bar?" },
      { question: "Qual reality renderia boa estrategia?", impostorQuestion: "Qual reality renderia boas fofocas?" },
      { question: "Que musica faz todo mundo cantar junto?", impostorQuestion: "Que musica faz todo mundo dancar junto?" },
      { question: "Qual ator combina com comedia?", impostorQuestion: "Qual ator combina com suspense?" },
      { question: "Que jogo rende rivalidade saudavel?", impostorQuestion: "Que jogo rende cooperacao total?" },
      { question: "Qual personagem parece um bom lider?", impostorQuestion: "Qual personagem parece um bom parceiro de confusao?" },
      { question: "Que final de obra divide opinioes?", impostorQuestion: "Que final de obra une opinioes?" },
    ],
  },
  {
    key: "rotina",
    title: "Perguntas de Rotina",
    icon: "clock",
    mode: "question",
    items: [
      { question: "O que voce faz logo ao acordar?", impostorQuestion: "O que voce faz logo antes de dormir?" },
      { question: "Que tarefa voce resolve cedo?", impostorQuestion: "Que tarefa voce empurra ate tarde?" },
      { question: "Qual item mora na sua mochila?", impostorQuestion: "Qual item mora na sua mesa?" },
      { question: "Que refeicao organiza seu dia?", impostorQuestion: "Que refeicao fecha seu dia?" },
      { question: "Qual momento pede silencio?", impostorQuestion: "Qual momento pede companhia?" },
      { question: "Que notificacao voce abre na hora?", impostorQuestion: "Que notificacao voce ignora na hora?" },
      { question: "Qual habito parece pequeno mas ajuda muito?", impostorQuestion: "Qual habito parece pequeno mas atrapalha muito?" },
      { question: "Que lugar da cidade faz parte da sua semana?", impostorQuestion: "Que lugar da cidade faz parte do seu fim de semana?" },
      { question: "Qual roupa voce repete sem culpa?", impostorQuestion: "Qual roupa voce guarda para ocasioes especiais?" },
      { question: "Que som costuma acompanhar seu trabalho?", impostorQuestion: "Que som costuma acompanhar seu descanso?" },
      { question: "Qual app agiliza sua vida?", impostorQuestion: "Qual app consome seu tempo?" },
      { question: "Que decisao diaria voce toma no automatico?", impostorQuestion: "Que decisao diaria voce repensa demais?" },
    ],
  },
];
