import { mutation } from "./_generated/server.js";

const DEFAULT_WORDS = [
  // Objetos Comuns
  { category: "Objeto", word: "Boné", hint: "Acessório para cabeça" },
  { category: "Objeto", word: "Óculos", hint: "Acessório para o rosto" },
  { category: "Objeto", word: "Celular", hint: "Aparelho eletrônico" },
  { category: "Objeto", word: "Relógio", hint: "Acessório de pulso" },
  { category: "Objeto", word: "Mochila", hint: "Usado para carregar coisas" },
  { category: "Objeto", word: "Tesoura", hint: "Instrumento de corte" },
  { category: "Objeto", word: "Caderno", hint: "Artigo de papelaria" },
  { category: "Objeto", word: "Caneta", hint: "Artigo de papelaria" },
  { category: "Objeto", word: "Chave", hint: "Usado em portas" },
  { category: "Objeto", word: "Carteira", hint: "Usado no bolso" },
  { category: "Objeto", word: "Espelho", hint: "Quarto ou banheiro" },
  { category: "Objeto", word: "Copo", hint: "Utensílio de cozinha" },
  { category: "Objeto", word: "Prato", hint: "Utensílio de cozinha" },
  { category: "Objeto", word: "Garfo", hint: "Talher" },
  { category: "Objeto", word: "Faca", hint: "Talher" },
  { category: "Objeto", word: "Colher", hint: "Talher" },
  { category: "Objeto", word: "Vassoura", hint: "Item de limpeza" },
  { category: "Objeto", word: "Balde", hint: "Item de limpeza" },
  { category: "Objeto", word: "Sabonete", hint: "Item de higiene" },
  { category: "Objeto", word: "Shampoo", hint: "Item de higiene" },
  { category: "Objeto", word: "Perfume", hint: "Cosmético" },
  { category: "Objeto", word: "Almofada", hint: "Sala de estar" },
  { category: "Objeto", word: "Travesseiro", hint: "Quarto" },
  { category: "Objeto", word: "Lençol", hint: "Cama" },
  { category: "Objeto", word: "Toalha", hint: "Banheiro" },
  { category: "Objeto", word: "Cadeira", hint: "Móvel compacto" },
  { category: "Objeto", word: "Mesa", hint: "Móvel" },
  { category: "Objeto", word: "Sofá", hint: "Móvel" },
  { category: "Objeto", word: "Cama", hint: "Móvel" },
  { category: "Objeto", word: "Televisão", hint: "Eletrodoméstico" },
  { category: "Objeto", word: "Geladeira", hint: "Eletrodoméstico" },
  { category: "Objeto", word: "Fogão", hint: "Eletrodoméstico" },
  { category: "Objeto", word: "Computador", hint: "Aparelho eletrônico" },
  { category: "Objeto", word: "Teclado", hint: "Acessório de informática" },
  { category: "Objeto", word: "Mouse", hint: "Acessório de informática" },
  { category: "Objeto", word: "Ventilador", hint: "Eletrodoméstico" },
  { category: "Objeto", word: "Abajur", hint: "Iluminação" },
  
  // Animais
  { category: "Animal", word: "Cachorro", hint: "Animal doméstico" },
  { category: "Animal", word: "Gato", hint: "Animal doméstico" },
  { category: "Animal", word: "Pássaro", hint: "Mascote" },
  { category: "Animal", word: "Cavalo", hint: "Fazenda" },
  { category: "Animal", word: "Vaca", hint: "Fazenda" },
  { category: "Animal", word: "Porco", hint: "Fazenda" },
  { category: "Animal", word: "Galinha", hint: "Ave" },
  { category: "Animal", word: "Pato", hint: "Ave" },
  { category: "Animal", word: "Leão", hint: "Felino selvagem" },
  { category: "Animal", word: "Tigre", hint: "Felino selvagem" },
  { category: "Animal", word: "Elefante", hint: "Selvagem pesado" },
  { category: "Animal", word: "Girafa", hint: "Selvagem alto" },
  { category: "Animal", word: "Macaco", hint: "Habilidade de subir" },
  { category: "Animal", word: "Urso", hint: "Floresta / Frio" },
  { category: "Animal", word: "Lobo", hint: "Canídeo selvagem" },
  { category: "Animal", word: "Cobra", hint: "Répteis" },
  { category: "Animal", word: "Tartaruga", hint: "Protegida / Devagar" },
  { category: "Animal", word: "Sapo", hint: "Anfíbio" },
  { category: "Animal", word: "Peixe", hint: "Vida aquática" },
  { category: "Animal", word: "Tubarão", hint: "Predador do mar" },
  { category: "Animal", word: "Baleia", hint: "Gigante do mar" },
  { category: "Animal", word: "Golfinho", hint: "Esperto do mar" },
  { category: "Animal", word: "Abelha", hint: "Inseto voador" },
  { category: "Animal", word: "Borboleta", hint: "Inseto bonito" },
  { category: "Animal", word: "Aranha", hint: "Criatura de 8 pernas" },
  
  // Natureza
  { category: "Natureza", word: "Árvore", hint: "Paisagem verde" },
  { category: "Natureza", word: "Flor", hint: "Paisagem colorida" },
  { category: "Natureza", word: "Grama", hint: "Chão verde" },
  { category: "Natureza", word: "Folha", hint: "Cai no chão" },
  { category: "Natureza", word: "Montanha", hint: "Relevo alto" },
  { category: "Natureza", word: "Rio", hint: "Água doce" },
  { category: "Natureza", word: "Mar", hint: "Água salgada" },
  { category: "Natureza", word: "Praia", hint: "Lugar de descanso" },
  { category: "Natureza", word: "Sol", hint: "Luz natural" },
  { category: "Natureza", word: "Lua", hint: "No céu noturno" },
  { category: "Natureza", word: "Estrela", hint: "Brilha de noite" },
  { category: "Natureza", word: "Nuvem", hint: "Fica no céu" },
  { category: "Natureza", word: "Chuva", hint: "Tempo ruim" },
  { category: "Natureza", word: "Vento", hint: "Sensação do tempo" },
  { category: "Natureza", word: "Neve", hint: "Tempo muito frio" },
  { category: "Natureza", word: "Gelo", hint: "Pode derreter" },
  
  // Locais
  { category: "Lugar", word: "Casa", hint: "Onde as pessoas moram" },
  { category: "Lugar", word: "Apartamento", hint: "Tipo de moradia" },
  { category: "Lugar", word: "Escola", hint: "Instituição educacional" },
  { category: "Lugar", word: "Faculdade", hint: "Instituição de ensino superior" },
  { category: "Lugar", word: "Hospital", hint: "Serviço de saúde" },
  { category: "Lugar", word: "Farmácia", hint: "Vende saúde" },
  { category: "Lugar", word: "Supermercado", hint: "Comércio de produtos básicos" },
  { category: "Lugar", word: "Padaria", hint: "Comércio de comida rápida" },
  { category: "Lugar", word: "Restaurante", hint: "Local de refeições sociais" },
  { category: "Lugar", word: "Pizzaria", hint: "Comércio noturno" },
  { category: "Lugar", word: "Bar", hint: "Entretenimento adulto" },
  { category: "Lugar", word: "Cinema", hint: "Entretenimento visual" },
  { category: "Lugar", word: "Teatro", hint: "Cultura" },
  { category: "Lugar", word: "Museu", hint: "Passeio cultural" },
  { category: "Lugar", word: "Parque", hint: "Lazer ao ar livre" },
  { category: "Lugar", word: "Praça", hint: "Espaço público" },
  { category: "Lugar", word: "Igreja", hint: "Ambiente religioso" },
  { category: "Lugar", word: "Templo", hint: "Ambiente religioso" },
  { category: "Lugar", word: "Banco", hint: "Serviços financeiros" },
  { category: "Lugar", word: "Correios", hint: "Serviço logístico" },
  { category: "Lugar", word: "Delegacia", hint: "Segurança" },
  { category: "Lugar", word: "Aeroporto", hint: "Transporte nacional/internacional" },
  { category: "Lugar", word: "Rodoviária", hint: "Transporte intermunicipal" },
  { category: "Lugar", word: "Estação", hint: "Transporte urbano principal" },
  { category: "Lugar", word: "Ponto", hint: "Espera de transporte urbano" },
  { category: "Lugar", word: "Estádio", hint: "Esportes e shows" },
  { category: "Lugar", word: "Academia", hint: "Esportes e saúde" },
  { category: "Lugar", word: "Clube", hint: "Lazer social" },
  { category: "Lugar", word: "Loja", hint: "Varejo" },
  { category: "Lugar", word: "Shopping", hint: "Centro de compras" },
  { category: "Lugar", word: "Rua", hint: "Via pública" },
  { category: "Lugar", word: "Avenida", hint: "Via pública importante" },
  { category: "Lugar", word: "Rodovia", hint: "Via pública de alta velocidade" },
  { category: "Lugar", word: "Ponte", hint: "Construção de passagem" },
  { category: "Lugar", word: "Túnel", hint: "Construção por baixo" },
  { category: "Lugar", word: "Edifício", hint: "Construção alta" },
  { category: "Lugar", word: "Castelo", hint: "Construção da nobreza" },
  
  // Veículos
  { category: "Veículo", word: "Carro", hint: "Veículo pessoal de 4 rodas" },
  { category: "Veículo", word: "Moto", hint: "Veículo pessoal de 2 rodas" },
  { category: "Veículo", word: "Bicicleta", hint: "Veículo movido a força humana" },
  { category: "Veículo", word: "Ônibus", hint: "Transporte de muitas pessoas" },
  { category: "Veículo", word: "Caminhão", hint: "Transporte de cargas" },
  { category: "Veículo", word: "Metrô", hint: "Transporte urbano sobre trilhos subterrâneo" },
  { category: "Veículo", word: "Trem", hint: "Transporte sobre trilhos" },
  { category: "Veículo", word: "Avião", hint: "Transporte no ar rápido" },
  { category: "Veículo", word: "Helicóptero", hint: "Transporte no ar vertical" },
  { category: "Veículo", word: "Navio", hint: "Transporte aquático grande" },
  { category: "Veículo", word: "Barco", hint: "Transporte aquático pequeno" },
  { category: "Veículo", word: "Submarino", hint: "Transporte por baixo da água" },
  { category: "Veículo", word: "Foguete", hint: "Veículo espacial" },
  { category: "Veículo", word: "Trator", hint: "Veículo rural/agrícola" },
  { category: "Veículo", word: "Carroça", hint: "Veículo de tração animal" },
  { category: "Veículo", word: "Ambulância", hint: "Veículo de emergência médica" },
  { category: "Veículo", word: "Viatura", hint: "Veículo de emergência de segurança" },
  
  // Vestimenta
  { category: "Vestimenta", word: "Camisa", hint: "Parte de cima" },
  { category: "Vestimenta", word: "Camiseta", hint: "Parte de cima casual" },
  { category: "Vestimenta", word: "Calça", hint: "Parte de baixo comprida" },
  { category: "Vestimenta", word: "Bermuda", hint: "Parte de baixo curta" },
  { category: "Vestimenta", word: "Shorts", hint: "Parte de baixo curta casual" },
  { category: "Vestimenta", word: "Saia", hint: "Roupões sem pernas separadas" },
  { category: "Vestimenta", word: "Vestido", hint: "Cobre corpo inteiro sem separar pernas" },
  { category: "Vestimenta", word: "Casaco", hint: "Roupa de frio espessa" },
  { category: "Vestimenta", word: "Jaqueta", hint: "Roupa de frio externa" },
  { category: "Vestimenta", word: "Blusa", hint: "Parte superior focada em mulheres ou frio leve" },
  { category: "Vestimenta", word: "Moletom", hint: "Agasalho muito confortável" },
  { category: "Vestimenta", word: "Meia", hint: "Calçado por baixo" },
  { category: "Vestimenta", word: "Cueca", hint: "Por baixo das calças" },
  { category: "Vestimenta", word: "Calcinha", hint: "Por baixo da roupa (mulher)" },
  { category: "Vestimenta", word: "Sutiã", hint: "Vestimenta de suporte (mulher)" },
  { category: "Vestimenta", word: "Biquíni", hint: "Roupa de praia/piscina" },
  { category: "Vestimenta", word: "Maiô", hint: "Moda praia inteiriço" },
  { category: "Vestimenta", word: "Sunga", hint: "Moda masculina piscina" },
  { category: "Vestimenta", word: "Sapato", hint: "Calçado formal" },
  { category: "Vestimenta", word: "Tênis", hint: "Calçado confortável/esporte" },
  { category: "Vestimenta", word: "Bota", hint: "Calçado de frio/proteção" },
  { category: "Vestimenta", word: "Sandália", hint: "Calçado aberto de tiras" },
  { category: "Vestimenta", word: "Chinelo", hint: "Calçado casual para casa" },
  { category: "Vestimenta", word: "Luva", hint: "Para aquecer braço" },
  { category: "Vestimenta", word: "Cachecol", hint: "Para pescoço/frio" },
  { category: "Vestimenta", word: "Cinto", hint: "Acessório para segurar roupa" },
  { category: "Vestimenta", word: "Gravata", hint: "Acessório formal de pescoço" },
];

export const seedData = mutation({
  handler: async (ctx) => {
    // Apaga registros antigos se existirem, para sempre substituir
    const existingWords = await ctx.db.query("wordPacks").collect();
    for (const w of existingWords) {
      await ctx.db.delete(w._id);
    }
    
    let count = 0;
    for (const { word, hint, category } of DEFAULT_WORDS) {
      await ctx.db.insert("wordPacks", {
        word,
        hint,
        category,
      });
      count++;
    }
    
    return `Inserido ${count} palavras no banco!`;
  },
});
