export const THEME_ICON_MAP: Record<string, string> = {
  star: "solar:star-bold",
  football: "solar:ball-bold",
  health: "solar:health-bold",
  laptop: "solar:laptop-bold",
  sparkles: "solar:magic-stick-3-bold",
  bolt: "solar:flash-bold",
  leaf: "solar:leaf-bold",
  target: "solar:target-bold",
  swords: "solar:sledgehammer-bold",
  pickaxe: "solar:hammer-bold",
  skull: "solar:skull-bold",
  blaster: "solar:rocket-bold",
  pokeball: "solar:planet-bold",
  lightsaber: "solar:sword-bold",
  crown: "solar:crown-bold",
  fist: "solar:bolt-circle-bold",
  katana: "solar:danger-triangle-bold",
  coffee: "solar:cup-bold",
  shield: "solar:shield-bold",
  castle: "solar:buildings-bold",
  folder: "solar:folder-bold",
  clock: "solar:clock-circle-bold",
};
